name: Update WakaTime Stats

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          # Branch - newer GitHub repositories have "master" as default branch, change to master in that case, default is master
          BRANCH: 'master'
          # Manual Commit messages - write your own messages here
          COMMIT_MSG: 'Automated Coding Activity Update ⚡'
